name: flutter_split_project
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"


dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  top_snackbar_flutter: ^2.1.1
  flutter_screenutil: ^5.5.3+2
  get: ^4.6.3
  dio: ^4.0.4
  flutter_easyloading: ^3.0.3
  hive: ^2.0.5
  hive_flutter: ^1.1.0
  grouped_list: ^5.1.2
  intl: ^0.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.0.5
  hive_generator: ^1.1.2
  flutter_svg: ^1.0.0
  pie_chart: ^5.3.2
  flutter_staggered_animations: ^1.0.0
  skeletons: ^0.0.3
  flutter_switch: ^0.3.2
  google_maps_widget: ^1.0.4

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/


  fonts:
    - family: Inter
      fonts:
        - asset: fonts/Inter-ExtraBold.ttf
          weight: 800
        - asset: fonts/Inter-Bold.ttf
          weight: 700
        - asset: fonts/Inter-SemiBold.ttf
          weight: 600
        - asset: fonts/Inter-Medium.ttf
          weight: 500
        - asset: fonts/Inter-Regular.ttf
          weight: 400
        - asset: fonts/Inter-Thin.ttf
          weight: 300
        - asset: fonts/Inter-Light.ttf
          weight: 200
        - asset: fonts/Inter-ExtraLight.ttf
          weight: 100

